name: fi-prh
on:
  workflow_dispatch:
    inputs:
      dates:
        description: "Comma list of financialDate(s) YYYY-MM-DD"
        required: true
        default: "2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31"
      limit:
        description: "Max XBRLs per date"
        required: true
        default: "200"
      soft_minutes:
        description: "Soft time budget (<=300)"
        required: true
        default: "290"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run list and download (soft time budget)
        shell: bash
        run: |
          set -e
          mkdir -p out/FI
          IFS=',' read -ra D <<< "${{ inputs.dates }}"
          limit="${{ inputs.limit }}"
          soft=$(( ${{ inputs.soft_minutes }} * 60 ))
          start=$(date +%s)
          for d in "${D[@]}"; do
            now=$(date +%s); elapsed=$((now-start))
            if [ "$elapsed" -ge "$soft" ]; then echo "Soft time budget hit ($elapsed s)"; break; fi
            d="$(echo "$d" | xargs)"
            echo "DATE $d"
            python countries/fi_prh_fetch.py --action list --financial-date "$d" --out out/FI
            python countries/fi_prh_fetch.py --action download --financial-date "$d" --limit "$limit" --out out/FI || true
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fi-${{ inputs.dates }}
          path: out/FI/**
          retention-days: 7
