name: fr-rne-api
on:
  workflow_dispatch:
    inputs:
      sirens:
        description: "Comma list of SIRENs"
        required: true
        default: "552100554"
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Login and download
        env:
          INPI_USER: ${{ secrets.INPI_USER }}
          INPI_PASS: ${{ secrets.INPI_PASS }}
        run: |
          mkdir -p out/FR
          python countries/fr_rne_fetch.py --action login --user "$INPI_USER" --password "$INPI_PASS" --token-file out/FR/inpi_token.json
          IFS=',' read -ra S <<< "${{ inputs.sirens }}"
          for s in "${S[@]}"; do
            python countries/fr_rne_fetch.py --action list-attachments --siren "$s" --token-file out/FR/inpi_token.json --out out/FR
            python countries/fr_rne_fetch.py --action download-attachments --siren "$s" --token-file out/FR/inpi_token.json --out out/FR
          done
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fr-rne
          path: out/FR/**
          retention-days: 7
