name: ie-cro
on:
  workflow_dispatch:
    inputs:
      years:
        description: "Comma list of years (e.g. 2023,2022)"
        required: true
        default: "2023,2022"
      soft_minutes:
        description: "Soft time budget (<=300)"
        required: true
        default: "290"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run fetch (multi-year, soft budget)
        shell: bash
        run: |
          set -e
          mkdir -p out/IE
          IFS=',' read -ra Y <<< "${{ inputs.years }}"
          soft=$(( ${{ inputs.soft_minutes }} * 60 ))
          start=$(date +%s)
          for y in "${Y[@]}"; do
            now=$(date +%s); elapsed=$((now-start))
            if [ "$elapsed" -ge "$soft" ]; then echo "Soft time budget hit ($elapsed s)"; break; fi
            y="$(echo "$y" | xargs)"
            echo "YEAR $y"
            python countries/ie_cro_fetch.py --action fetch --year "$y" --out out/IE || true
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ie-${{ inputs.years }}
          path: out/IE/**
          retention-days: 7
