name: ie-cro
on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year (2022 or 2023)"
        required: true
        default: "2023"
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run fetch
        run: |
          mkdir -p out/IE
          python countries/ie_cro_fetch.py --action fetch --year "${{ inputs.year }}" --out out/IE
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ie-${{ inputs.year }}
          path: out/IE/**
          retention-days: 7
