name: nl-kvk
on:
  workflow_dispatch:
    inputs:
      parts:
        description: "Comma list of parts (e.g. 0,1,2,3,4)"
        required: true
        default: "0"
      soft_minutes:
        description: "Soft time budget (<=300)"
        required: true
        default: "290"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download parts (soft budget)
        shell: bash
        run: |
          set -e
          mkdir -p out/NL/bulk
          IFS=',' read -ra P <<< "${{ inputs.parts }}"
          soft=$(( ${{ inputs.soft_minutes }} * 60 ))
          start=$(date +%s)
          for i in "${P[@]}"; do
            now=$(date +%s); elapsed=$((now-start))
            if [ "$elapsed" -ge "$soft" ]; then echo "Soft time budget hit ($elapsed s)"; break; fi
            i="$(echo "$i" | xargs)"
            url="https://www.kvk.nl/download/kvk-open-data-set-jaarrekeningen${i}.zip"
            echo "GET $url"
            curl -fsSL "$url" -o "out/NL/bulk/kvk_jaarrekeningen_part${i}.zip" || true
          done

      - name: Bundle zips and sample xml tar
        shell: bash
        run: |
          python countries/nl_kvk_pack_and_parse.py --action bundle-zips --folder out/NL/bulk --out out/NL/bulk/nl_kvk_zip_parts.tar.gz
          if [ -f out/NL/bulk/kvk_jaarrekeningen_part0.zip ]; then
            python countries/nl_kvk_pack_and_parse.py --action pack-xml --zip out/NL/bulk/kvk_jaarrekeningen_part0.zip --out out/NL/bulk/nl_part0_xmls.tar.gz
          fi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nl-kvk-${{ inputs.parts }}
          path: out/NL/**
          retention-days: 7
